version: '3.8'

services:
  webserver:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.9.1-python3.9
    container_name: airflow-webserver
    env_file: .env
    volumes:
      - airflow_data:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./mlruns:/opt/airflow/mlruns
    ports:
      - "8080:8080"
    depends_on:
      - scheduler
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow webserver
      "

  scheduler:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.9.1-python3.9
    container_name: airflow-scheduler
    env_file: .env
    volumes:
      - airflow_data:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./mlruns:/opt/airflow/mlruns
    command: airflow scheduler

  mlflow:
    user: "0:0"
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri /opt/airflow/mlruns --default-artifact-root /opt/airflow/mlruns
    volumes:
      - ./mlruns:/opt/airflow/mlruns

volumes:
  airflow_data:
